MAX_PLAYERS_PER_ROOM = 8
MIN_PLAYERS_TO_START = 2

MAX_PUBLIC_MESSAGE_HISTORY = 50
# NOTE: MAX_CHAT_LENGTH is defined in server/utils/validation.py (500)

WS_TIMEOUT_SECONDS = 30.0
WS_MAX_RECONNECT_ATTEMPTS = 5
WS_BASE_RECONNECT_DELAY_MS = 1000

DM_CHAT_RATE_LIMIT_SECONDS = 30
DM_OPENING_DELAY_SECONDS = 10

VALID_PHASES = ["waiting", "playing", "trial", "revealed", "finished"]

ACT_UNLOCK_MAP = {"act1": "2", "act2": "3"}

CONSENSUS_THRESHOLD = 0.5
